---
#Ansible Playbook to build and push Docker image to ECR
- name: Playbook to build and run Docker
  hosts: dev-servers
  become: true
  gather_facts: false
  tasks:

    - name: Establish connection to ECR
      shell: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 469677591456.dkr.ecr.us-west-2.amazonaws.com

    - name: Pull the image from ECR
      shell: docker pull 469677591456.dkr.ecr.us-west-2.amazonaws.com/udapeapeople:latest

    - name: Run the container using the docker image
      shell: docker run --name=springbootapp --detach 469677591456.dkr.ecr.us-west-2.amazonaws.com/udapeapeople:latest
